### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-projektor#20]
- [x] Ansichts-Navigation: Box höher machen so dass unterstes Icon mindestens denselben Abstand zur Unterkante hat wie oberes zu "Ansicht"
- [x] Mail-Button: keine Border
- [x] Petri-Schale: Abstand zwischen Rand und Nodes!
- [x] Projekt-Pop-Over: Alle Schriften mindestens + 30%, Breite des Pop-Overs anpassen
- [x] Schließen-Button für Filter- & Projekt-Pop-Over (oben rechts)
- [x] Farbe der Jahr-Striche bei Timeline-Diagramm ändern: #989aa1
- [x] Wiki-Link als Button im Popover (gleicher wie mail und links davon, mit text "WIKI")
- [x] Wenn "Kein […] verfübar" anfügen: "In Wiki 'href' bearbeiten" 
- [x] Exitbutton (exit.svg) bei allen popovers rechts oben von modal
- [x] Ordnerstruktur: Timeline & Area in eigene Ordner
- [x] Project-Popover: ListBox-Title auch in TextBoxen außer titel, beschreibung & icon, font-größe dementsprechend anpassen
